import { type Bump, type ChangeSize, maxChangeSize } from "./change.ts"
import type { NamedPackage } from "./deno.ts"
import { printVersion, type Version } from "./version.ts"

export type Package = {
	path: string
	json: NamedPackage
	version: Version
	unreleasedChanges: Bump[]
	changelog: string[]
}

export function bumpVersion(version: Version, scale: ChangeSize) {
	if (scale === "epoch") {
		version.epoch++
		version.major = 0
		version.minor = 0
		version.patch = 0
	} else if (scale === "major") {
		version.major++
		version.minor = 0
		version.patch = 0
	} else if (scale === "minor") {
		version.minor++
		version.patch = 0
	} else if (scale === "patch") {
		version.patch++
	}
}

export function releasePackage(pkg: Package) {
	const scale = maxChangeSize(...pkg.unreleasedChanges.map((it) => it.type))
	bumpVersion(pkg.version, scale)
	pkg.changelog.push(`\n## ${printVersion(pkg.version)}`)
	for (const change of pkg.unreleasedChanges)
		pkg.changelog.push(`\t- (${change.type}) ${change.name}`)
	pkg.unreleasedChanges = []
}

export async function packageFromJsonPath(path: string): Promise<Package> {
	const json: NamedPackage = JSON.parse(
		await Deno.readTextFile(path),
	)
	return {
		path,
		json,
		version: {
			epoch: 0,
			major: 0,
			minor: 0,
			patch: 0,
		},
		unreleasedChanges: [],
		changelog: [
			`# ${json.name}`,
			`*this changelog is autogenerated by [@beo/version](https://jsr.io/@beo/version)`,
		],
	}
}
