
[[change]]
name = "Create a scrappy version manager"
package = "@beo/version"
type = "minor"

[[change]]
name = "Create a scrappy global stability manager"
package = "@beo/global"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Let JSR read the module documentation"
package = "@beo/version"
type = "patch"

[[change]]
name = "Let JSR read the module documentation"
package = "@beo/global"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Reword the module documentation"
package = "@beo/global"
type = "patch"

[[change]]
name = "Improve the documentation on JSR"
package = "@beo/version"
type = "patch"

[[change]]
name = "Create a pretty dang fast signal engine"
package = "@beo/signal"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Fix a bug where we bump package versions even if no changes are made"
package = "@beo/version"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Add proper documentation"
package = "@beo/signal"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Use globalThis instead of window"
package = "@beo/global"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Blocked adding a release when a release just occurred with no changes"
package = "@beo/version"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Close the code fence on the main module documentation"
package = "@beo/signal"
type = "patch"

[[change]]
name = "Add a framework-independent DOM library"
package = "@beo/omni"
type = "minor"

[[change]]
name = "Add an HTML omni implemtnation"
package = "@beo/omni-web"
type = "minor"

[[change]]
name = "Create a simple lil errors library"
package = "@beo/error"
type = "minor"

[[change]]
name = "Automatically print deno.json files in a standard order"
package = "@beo/version"
type = "minor"
