
[[change]]
name = "Create a scrappy version manager"
package = "@beo/version"
type = "minor"

[[change]]
name = "Create a scrappy global stability manager"
package = "@beo/global"
type = "minor"

[[change]]
type = "release"