
[[change]]
name = "Create a scrappy version manager"
package = "@beo/version"
type = "minor"

[[change]]
name = "Create a scrappy global stability manager"
package = "@beo/global"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Let JSR read the module documentation"
package = "@beo/version"
type = "patch"

[[change]]
name = "Let JSR read the module documentation"
package = "@beo/global"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Reword the module documentation"
package = "@beo/global"
type = "patch"

[[change]]
name = "Improve the documentation on JSR"
package = "@beo/version"
type = "patch"

[[change]]
name = "Create a pretty dang fast signal engine"
package = "@beo/signal"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Fix a bug where we bump package versions even if no changes are made"
package = "@beo/version"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Add proper documentation"
package = "@beo/signal"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Use globalThis instead of window"
package = "@beo/global"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Blocked adding a release when a release just occurred with no changes"
package = "@beo/version"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Close the code fence on the main module documentation"
package = "@beo/signal"
type = "patch"

[[change]]
name = "Add a framework-independent DOM library"
package = "@beo/omni"
type = "minor"

[[change]]
name = "Add an HTML omni implemtnation"
package = "@beo/omni-web"
type = "minor"

[[change]]
name = "Create a simple lil errors library"
package = "@beo/error"
type = "minor"

[[change]]
name = "Automatically print deno.json files in a standard order"
package = "@beo/version"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Add documentation"
package = "@beo/error"
type = "patch"

[[change]]
name = "Add documentation"
package = "@beo/omni-web"
type = "patch"

[[change]]
name = "Add example for JSR"
package = "@beo/omni-web"
type = "patch"

[[change]]
name = "Add documentation for JSR"
package = "@beo/omni"
type = "patch"

[[change]]
name = "Fix code fence in documentation that broke visibility on JSR"
package = "@beo/signal"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Fix support for packages without names"
package = "@beo/version"
type = "patch"

[[change]]
name = "Fix awful documentation"
package = "@beo/omni"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Create a teeny virtual dom library"
package = "@beo/vdom"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Write documentation"
package = "@beo/vdom"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Fix bugs in documentation because I'm dumb"
package = "@beo/vdom"
type = "patch"

[[change]]
type = "release"

[[change]]
name = "Add public-facing living listeners API"
package = "@beo/vdom"
type = "minor"

[[change]]
type = "release"

[[change]]
name = "Improve types"
package = "@beo/omni"
type = "patch"

[[change]]
name = "Allow VDOMElement to take an element name"
package = "@beo/vdom"
type = "minor"

[[change]]
name = "Add `defer` api"
package = "@beo/vdom"
type = "minor"

[[change]]
name = "Don't throw when setting no children on a text node"
package = "@beo/omni-web"
type = "patch"

[[change]]
name = "Add internal composition API"
package = "@beo/framework"
type = "minor"

[[change]]
name = "Create a simple logging framework"
package = "@beo/log"
type = "minor"

[[change]]
name = "Add setAttribute to VDOMElement"
package = "@beo/vdom"
type = "minor"
